name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io --username sc3p73r-it --password-stdin

    - name: Build Image
      run: docker build -t ghcr.io/sc3p73r-it/nodejsapp:v2 .

    - name: Push Image
      run: docker push ghcr.io/sc3p73r-it/nodejsapp:v2
